### ISSUE TITLE
Work distribution

### ISSUE THREAD

**Issue by miguelc3** [miguelc3/TestAssignment1#1]
Hi, I've already finished time mode (I will add some comments later) and since Fady hasn't responded to my e-mail yet, I think I'll start argparse soon.
So, when you finish the other mode of play please say something so that we can test it.
I think it's ok if you complete my file or do it in a different file and then I can merge the two files.

**Comment by joaodmatias** [comment]
Hey, I'm gonna try to merge the file I wrote with yours and test it then I'll put it here. Just tell me something, do we have to choose the gamemode before the game begins (with argparse maybe) or they can coexist?
For example, I can start the game and finish because the time finished or before the time finished but I pressed the maximum number of characters.
I don't know if you get what I mean.

**Comment by joaodmatias** [comment]
I'm also gonna start on argparse to choose the game mode

**Comment by joaodmatias** [comment]
I already have argparse working

**Comment by miguelc3** [comment]
Yes, I understood. I think that they can not coexist. If you choose a game mode, that's how you going to play it until the end. At least that's what I think.
Mine was also almost done xD
But, therefore, let me merge all the files and comment what needs to be comment. You already worked enough ahah
Can you comit the files from your pycharm to github, please?

**Comment by joaodmatias** [comment]
I did it in your file and already commited it. Check it out. Still have to change a few things because my prints and colors are different from yours, and to keep it even. Let me just finish the stats part and all that.

**Comment by miguelc3** [comment]
That problem on line 143 is kinda weird ... Anyway, I'm now commenting all the code and I will try to figure it out what's the problem with that for cycle.
Everything looks like its working fine ... but, what do u think about putting the argparse part and the empty lists inside def main() as the professor did in class?
Btw, I think you told me that tomorrow you have classes with Fady? If yes, can you talk with him? Because he didn't say anything and I don't know what to do about it...

**Comment by joaodmatias** [comment]
Hey, if it works I'm cool with it ahah. Yeah I'm supposed to have a class with him tomorrow, if he appears I'll talk to him, cause I don't know what to do as well :/.

**Comment by miguelc3** [comment]
I think everything is fine now. Please test it yourself to see if you get some problem.
I add some things like, if the user gets all the inputs right the program gave an error of division by 0, i fixed it.
Also, if we write in the terminal just './main.py' without any argument it would run the max_inputs mode forever, I also added an if statement for those cases.
Btw, did u talk with Fady?
Feel free to respond on whatsapp
